{% set version = "3.0-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cardata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/carData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/carData/carData_{{ version }}.tar.gz
  sha256: cda6f5e3efc1d955a4a0625e9c33f90d49f5455840e88b3bd757129b86044724

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('carData')"           # [not win]
    - "\"%R%\" -e \"library('carData')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=carData, http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
  license: GPL (>= 2)
  summary: ' Datasets to Accompany J. Fox and S. Weisberg,  An R Companion to Applied Regression, Third Edition, Sage (forthcoming).'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: carData
# Version: 3.0-2
# Date: 2018-09-28
# Title: Companion to Applied Regression Data Sets
# Authors@R: c(person("John", "Fox", role = c("aut", "cre"), email = "jfox@mcmaster.ca"), person("Sanford", "Weisberg", role = "aut", email = "sandy@umn.edu"), person("Brad", "Price", role = "aut", email = "brad.price@mail.wvu.edu"))
# Depends: R (>= 3.0)
# LazyLoad: yes
# LazyData: yes
# Description:  Datasets to Accompany J. Fox and S. Weisberg,  An R Companion to Applied Regression, Third Edition, Sage (forthcoming).
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=carData, http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
# Author: John Fox [aut, cre], Sanford Weisberg [aut], Brad Price [aut]
# Maintainer: John Fox <jfox@mcmaster.ca>
# Repository: CRAN
# Repository/R-Forge/Project: car
# Repository/R-Forge/Revision: 566
# Repository/R-Forge/DateTimeStamp: 2018-09-28 16:36:37
# Date/Publication: 2018-09-30 16:00:03 UTC
# NeedsCompilation: no
# Packaged: 2018-09-28 16:50:10 UTC; rforge
