appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pJoccBz//1hI0/tHKj0DAmbl0FZretuXY7/Sfm0ndFRh6gOtqgkkcww7OfSKPGUm23YR08KzL+X6f0QRuU5sjnZwO9FgWBuiNS6esjm+BuyN/qrTJMbKJUlv14vSdIlbea//ztT3dv+3hJ165sTnCm2ILA/IsYkWrulDy1wJTmIKTX/Guur888ojPbtb/WWgcQFVWxhPbJa2UrJOWXS5NoAkqeYB+v0kaIdLaWi2fJQgiGS37hgUBahD105KupO/w4470MOO4f0t0lacuD2Mvqwil08DgCimYorp6z+FOBwYA3atumMnk3GcRB5l2p3+Bn/E0LbY9bu9D27qio21wtK9C80CNLnOouGtlxHSslkF8y2t4pwoJYn5q8k0h4WgMsLtURfdXhSoSwBSyC6ik8LlB95iiqAKKdSkD2eutbkSCZSreur2mHrBs16FU+orAKCJOfPNeJUCYsuHXPj6LRqSH/s7t3XcHrOWn27ijoXC0DAl+d9n8yfU9E20roqQ2LPLRcj2gCLzWmSMb+7LtCQZHM/yRcHEkB5xuux946xmYhtnkzf01ghGuOP+jO61dzzbXeIgyI01XkycdhAUWrJCxTdtObOomQ5qWmOjv1jwU4gUDOWmv+UA4XEHr+jzWxwdmUuJjkampZvV7DdwNm6d4KUD6BpIL2BgPyeAgjA=}
