travis:
  secure:
    BINSTAR_TOKEN: mR9oPFpMNot/dSkiT6RnhBgRaeZxxpxFQMRcsdKHsY+CBjwxzjW7Z4DZyjoPn2pCpIEHR+rMzB+DhlvSSv+IzaLCHu0YP7k/1MEgboBizwpQnJa1MC8awgWULU6epPoaITyI7fHJF+wIOeu67w/XaEe+AVdVRuY0O0peEq4VTV1b+XFfbyRshoPVbJ0l2ydvZnT3GVgToz/qphbuCUXwJEa43hY/aZXjzvaXibcNhTS865QRcAb6XZq1rcaWuMAGKskwBNwZz5I2mB7kTaLBh4/qVtBJFveLQU5yFnHOXOJ9R4kmPsok1Xs+C4BEMCSYodg/8wdYfPzTcfVXYfuWR/EbnzOst+SFN1FRA6797wD71mOMx3RKwQYrUuIlGF854Z2LSjgeQz9bRLnypFj5wGfDBguh53fPITFwLfOHKw1b6DBCb5GR4/Z5Ufz2hCDfHDFFcFRzzc7zMAXMinh5v9192m3bRjMFL1rQTaFX5wiKE8w/qtgsGU/R5P3jfk7ntIVSHrUpEib03cFnQMloL0X6GwU2Om8FG7B9nrNDRuV/9ZaDb82CrNptu6q/SXx8r7KgWCoZ+tBvPp4pxFYLZ9i6bneO+CO0XPBaVYESi8WoDAIwEMuGeSzXWdlJ2oPcghC9kbkEotmsQtcQUIVmVOx4BWsiffOh4Z0yBqqqGA8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
